name: Issue Interaction with ChatGPT

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-code-with-chatgpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract PR Diff
        run: |
          BASE_REF=${{ github.event.pull_request.base.sha }}
          HEAD_REF=${{ github.event.pull_request.head.sha }}
          git fetch origin $BASE_REF --depth=1
          git diff $BASE_REF $HEAD_REF > pr_diff.txt

      - name: Analyze Code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF_CONTENT=$(cat pr_diff.txt)
          INSTRUCTIONS="Based on the code diff below, please provide a summary of the major insights derived. Also, check for any potential issues or improvements.The response should be a concise summary without any additional formatting, markdown, or characters outside the summary text."
          FULL_PROMPT="$INSTRUCTIONS\n\n$DIFF_CONTENT"
          MESSAGES_JSON=$(jq -n --arg body "$FULL_PROMPT" '[{"role": "user", "content": $body}]')
          
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"model\": \"gpt-3.5-turbo\", \"messages\": $MESSAGES_JSON, \"max_tokens\": 500}")
          
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          
          if [[ -z "$SUMMARY" ]]; then
            echo "No summary found in the response. Please rerun the job."
            exit 1
          fi
          
          echo "$SUMMARY" > summary.txt

      - name: Post Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          response=$(cat summary.txt)
          comment_body=$(jq -n --arg body "$response" '{body: $body}')
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$comment_body" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/comments"
